//! PDB writer for matched-function exports (Windows / Binary Ninja).
//!
//! Builds a PDB whose DBI carries one `GlobalProc` + `Public` per matched
//! function, keyed into the PE's section table. The companion is keyed to the
//! image by the GUID/age/signature lifted from the PE debug directory, so a
//! debugger pairs it with the original automatically.
//!
//! PE-only: [`PdbWriter::write`] fails on non-PE images (no section table /
//! debug directory).

use anyhow::{Context, Result};
use pdb_sdk::{
    Guid,
    builders::{ModuleBuilder, PdbBuilder},
    codeview::{
        DataRegionOffset,
        symbols::{Procedure, ProcedureProperties, Public, PublicProperties, SymbolRecord},
        types::{CallingConvention, FunctionProperties, TypeRecord},
    },
    dbi::{SectionContrib, SectionHeader},
    utils::StrBuf,
};
use std::collections::HashMap;
use std::io::Write;
use std::path::Path;

use super::{ExportContext, MatchedFunction, SymbolWriter};
use crate::binary::Binary;

pub struct PdbWriter;

impl SymbolWriter for PdbWriter {
    fn label(&self) -> &str {
        "PDB"
    }

    fn write(
        &self,
        ctx: &ExportContext,
        matches: &[MatchedFunction],
        out: &mut dyn Write,
    ) -> Result<()> {
        let bin = ctx.bin;
        let pdb_info = extract_pdb_info(bin)?;

        let mut builder = PdbBuilder::default();
        builder.info().guid(Guid(pdb_info.guid));
        builder.info().age(pdb_info.age);
        builder.info().signature(pdb_info.timestamp);

        let sections = build_sections(bin, &mut builder)?;
        build_functions(bin, &mut builder, &sections, matches)?;

        builder
            .dbi()
            .symbols()
            .finish_publics()
            .add(SymbolRecord::EnvBlock {
                reserved: 0,
                fields: vec![StrBuf::new(
                    "PDB generated by: binfold/pdbgen_canary https://github.com/trumank/binfold\0\0",
                )],
            });

        // `PdbBuilder::commit` needs a seekable sink, but the trait gives us a
        // plain `Write`. Build into an in-memory cursor, then stream it out.
        let mut buf = std::io::Cursor::new(Vec::new());
        builder.commit(&mut buf)?;
        out.write_all(&buf.into_inner())?;
        Ok(())
    }
}

#[derive(Debug)]
struct PdbInfo {
    age: u32,
    timestamp: u32,
    guid: [u8; 16],
}

#[derive(Debug)]
struct SectionInfo {
    name: String,
    index: u16,
    virtual_address: u32,
    virtual_size: u32,
    characteristics: u32,
}

fn extract_pdb_info(bin: &Binary) -> Result<PdbInfo> {
    // PDB info from the PE debug directory.
    let pdb_debug_info = bin.pdb_info()?;
    Ok(PdbInfo {
        age: pdb_debug_info.age,
        timestamp: bin.timestamp()?,
        guid: pdb_debug_info.guid,
    })
}

fn build_sections(bin: &Binary, builder: &mut PdbBuilder) -> Result<Vec<SectionInfo>> {
    let mut sections = Vec::new();

    for (idx, section) in bin.sections()?.into_iter().enumerate() {
        let name = section.name()?;
        let mut name_array = [0u8; 8];
        let name_bytes = name.as_bytes();
        let len = name_bytes.len().min(8);
        name_array[..len].copy_from_slice(&name_bytes[..len]);

        let section_info = SectionInfo {
            name: name.to_string(),
            index: (idx as u16) + 1, // Section indices are 1-based in PDB
            virtual_address: section.virtual_address,
            virtual_size: section.virtual_size,
            characteristics: section.characteristics,
        };

        builder.dbi().add_section_header(SectionHeader {
            name: name_array,
            virtual_size: section.virtual_size,
            virtual_address: section.virtual_address,
            size_of_raw_data: section.size_of_raw_data,
            pointer_to_raw_data: section.pointer_to_raw_data,
            pointer_to_relocations: 0,
            pointer_to_line_numbers: 0,
            number_of_relocations: 0,
            number_of_line_numbers: 0,
            characteristics: section.characteristics,
        });

        sections.push(section_info);
    }

    Ok(sections)
}

fn build_functions(
    bin: &Binary,
    builder: &mut PdbBuilder,
    sections: &[SectionInfo],
    functions: &[MatchedFunction],
) -> Result<()> {
    // A simple void function type shared by every procedure.
    let void_fn_type = {
        let tpi = builder.tpi();

        let arg_list = tpi.add(
            "args",
            TypeRecord::ArgList {
                count: 0,
                arg_list: vec![],
            },
        );

        tpi.add(
            "void_func",
            TypeRecord::Procedure {
                return_type: None,
                calling_conv: CallingConvention::NearC,
                properties: FunctionProperties::new(),
                arg_count: 0,
                arg_list,
            },
        )
    };

    let base_address = bin.image_base();
    let mut functions_by_section: HashMap<u16, Vec<&MatchedFunction>> = HashMap::new();

    // Group functions by section.
    for function in functions {
        for section in sections {
            let section_start = base_address + section.virtual_address as u64;
            let section_end = section_start + section.virtual_size as u64;

            if (section_start..section_end).contains(&function.address) {
                functions_by_section
                    .entry(section.index)
                    .or_default()
                    .push(function);
                break;
            }
        }
    }

    // Create modules for each section with functions.
    for (section_idx, section_functions) in functions_by_section {
        let section = sections
            .iter()
            .find(|s| s.index == section_idx)
            .context("section not found")?;

        let section_start = base_address + section.virtual_address as u64;

        let sec_contrib = SectionContrib {
            i_sect: section_idx,
            pad1: [0, 0],
            offset: 0,
            size: section.virtual_size,
            characteristics: section.characteristics,
            i_mod: 0,
            pad2: [0, 0],
            data_crc: 0,
            reloc_crc: 0,
        };

        let mut module = ModuleBuilder::new(
            format!("{}_module", section.name),
            format!("/warp/{}.obj", section.name),
            sec_contrib,
        );

        for function in section_functions {
            let func_offset = (function.address - section_start) as u32;

            // Add to module.
            let proc_idx = module.symbols.len();
            module.add_symbol(SymbolRecord::GlobalProc(Procedure {
                parent: None,
                end: 0.into(),
                next: None,
                code_size: function.size as u32,
                dbg_start_offset: 0,
                dbg_end_offset: 0,
                function_type: void_fn_type,
                code_offset: DataRegionOffset::new(func_offset, section_idx),
                properties: ProcedureProperties::new(),
                name: StrBuf::new(function.name.to_string()),
            }));
            let end_idx = module.add_symbol(SymbolRecord::ProcEnd);
            match &mut module.symbols[proc_idx] {
                SymbolRecord::GlobalProc(proc) => proc.end = end_idx,
                _ => unreachable!(),
            }

            // Add to public symbols.
            builder.dbi().symbols().add(Public {
                properties: PublicProperties::new().with_is_function(true),
                offset: DataRegionOffset::new(func_offset, section_idx),
                name: StrBuf::new(function.name.to_string()),
            });
        }

        builder.dbi().add_module(module);
    }

    Ok(())
}

/// Check if a PDB file was generated by this tool (carries an `EnvBlock`
/// containing `pdbgen_canary`), so it's safe to overwrite. Used by the
/// `--generate-pdb` overwrite guard.
pub fn should_replace(pdb_path: &Path) -> Result<bool> {
    use crate::mmap_source::MmapSource;
    use pdb::{FallibleIterator, PDB, SymbolData};

    let mmap_source = MmapSource::new(pdb_path)
        .with_context(|| format!("Failed to memory-map PDB file: {pdb_path:?}"))?;

    let mut pdb = PDB::open(mmap_source)
        .with_context(|| format!("Failed to parse PDB file: {pdb_path:?}"))?;

    let global_symbols = pdb.global_symbols()?;
    let mut symbols = global_symbols.iter();

    while let Some(symbol) = symbols.next()? {
        if let Ok(SymbolData::EnvBlock(env_block)) = symbol.parse() {
            for entry in env_block.entries {
                if entry.to_string().contains("pdbgen_canary") {
                    return Ok(true);
                }
            }
        }
    }

    Ok(false)
}
